### ISSUE TITLE
Failed to execute script 'app' due to unhandled exception!

### ISSUE THREAD

**Issue by Erdalf** [octimot/StoryToolkitAI#102]
Hello, I've been using StoryToolkitAI for about a month without issues but today it randomly decided it doesn't want to open up. The CMD says:

Traceback (most recent call last):
File "app.py", line 12036, in <module>
File "app.py", line 11368, in __init__
File "app.py", line 11808, in check_update
ValueError: invalid literal for int() with base 10: 'untagged-204b520d0eef00d40d45'
[14500] Failed to execute script 'app' due to unhandled exception!

What should I do? Thanks!

**Comment by octimot** [comment]
Hey!

It seems there was a problem with GitHub when we published the latest release. Could you check now to see if you still experience the same thing?

Cheers

**Comment by Erdalf** [comment]
> Hey!
> 
> It seems there was a problem with GitHub when we published the latest release. Could you check now to see if you still experience the same thing?
> 
> Cheers

It seems to have been fixed. Thanks a lot! You are the best.
