### ISSUE TITLE
group questions error

### ISSUE THREAD

**Issue by pantau000** [octimot/StoryToolkitAI#113]
I get the following error just about when the grouping of questions is about to finish:

Classifying segments: 100%|██████████████████████████████████████████████████████████| 490/490 [47:47<00:00,  5.85s/it]
ERROR: Unable to execute task <bound method ToolkitOps.group_questions of <storytoolkitai.core.toolkit_ops.toolkit_ops.ToolkitOps object at 0x000001FCF239F400>> for queue item Caxias01.mp3(GroupQuestions)-1687266706.8332598
Traceback (most recent call last):
  File "D:\temp\StoryToolkitAI\StoryToolkitAI\storytoolkitai\..\storytoolkitai\core\toolkit_ops\processing_queue.py", line 735, in execute_item_tasks
    kwargs = task(**{**kwargs, **item})
  File "D:\temp\StoryToolkitAI\StoryToolkitAI\storytoolkitai\..\storytoolkitai\core\toolkit_ops\toolkit_ops.py", line 2140, in group_questions
    questions_group = transcription.prepare_transcript_group(
  File "D:\temp\StoryToolkitAI\StoryToolkitAI\storytoolkitai\..\storytoolkitai\core\toolkit_ops\transcription.py", line 1299, in prepare_transcript_group
    group_id = self.group_id_from_name(str(group_name))
  File "D:\temp\StoryToolkitAI\StoryToolkitAI\storytoolkitai\..\storytoolkitai\core\toolkit_ops\transcription.py", line 1263, in group_id_from_name
    group_id = "{}{}".format(group_name.strip().lower().replace(' ', ''), time.strftime('%Y%m%d%H%M%S%f'))
ValueError: Invalid format string

**Comment by octimot** [comment]
Is this happening every time you try that?

**Comment by pantau000** [comment]
Just tried again, happened again as soon as the classifying ends:

ERROR: Unable to execute task <bound method ToolkitOps.group_questions of <storytoolkitai.core.toolkit_ops.toolkit_ops.ToolkitOps object at 0x0000021F121CF460>> for queue item Caxias01.mp3(GroupQuestions)-1687347093.713171
Traceback (most recent call last):
  File "D:\temp\StoryToolkitAI\StoryToolkitAI\storytoolkitai\..\storytoolkitai\core\toolkit_ops\processing_queue.py", line 735, in execute_item_tasks
    kwargs = task(**{**kwargs, **item})
  File "D:\temp\StoryToolkitAI\StoryToolkitAI\storytoolkitai\..\storytoolkitai\core\toolkit_ops\toolkit_ops.py", line 2140, in group_questions
    questions_group = transcription.prepare_transcript_group(
  File "D:\temp\StoryToolkitAI\StoryToolkitAI\storytoolkitai\..\storytoolkitai\core\toolkit_ops\transcription.py", line 1299, in prepare_transcript_group
    group_id = self.group_id_from_name(str(group_name))
  File "D:\temp\StoryToolkitAI\StoryToolkitAI\storytoolkitai\..\storytoolkitai\core\toolkit_ops\transcription.py", line 1263, in group_id_from_name
    group_id = "{}{}".format(group_name.strip().lower().replace(' ', ''), time.strftime('%Y%m%d%H%M%S%f'))
ValueError: Invalid format string

**Comment by octimot** [comment]
We're unable to recreate this. What name are you using for the group?

**Comment by pantau000** [comment]
I just click on "group questions"

**Comment by octimot** [comment]
It looks like it was a Windows-specific error which passed our quality control.

I just pushed a patch, feel free to do a `git pull` and please let me know if it still doesn't work.

Cheers!

**Comment by pantau000** [comment]
Works smoothly now,, thanks!
