### ISSUE TITLE
Standalone not installing properly over old versions

### ISSUE THREAD

**Issue by octimot** [octimot/StoryToolkitAI#119]
Upon installing the Patreon version and running for the first time, I got this:

numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
C:\Users\mrgre\AppData\Local\Programs\StoryToolkitAI\numpy\.libs\libopenblas.FB5AE2TYXYH2IJRDKGDGQ3XBKLKTF43H.gfortran-win_amd64.dll
C:\Users\mrgre\AppData\Local\Programs\StoryToolkitAI\numpy\.libs\libopenblas64__v0.3.21-gcc_10_3_0.dll
  warnings.warn("loaded more than 1 DLL from .libs:"
ERROR: Traceback (most recent call last):
  File "storytoolkitai\__main__.py", line 57, in <module>
  File "pkg_resources\__init__.py", line 909, in require
  File "pkg_resources\__init__.py", line 800, in resolve
pkg_resources.ContextualVersionConflict: (decorator 5.1.1 (c:\users\mrgre\appdata\local\programs\storytoolkitai), Requirement.parse('decorator<5.0,>=4.0.2'), {'moviepy'})

WARNING: Some of the packages required to run StoryToolkitAI are missing from your Python environment.

WARNING:
If you are running the standalone version of the app, please report this error to the developers together with the log file found at: [app.log.txt](https://github.com/octimot/StoryToolkitAI/files/12002243/app.log.txt)
INFO: Running post-update tasks for 0.19.4...
INFO: Updated config file C:\Users\mrgre\StoryToolkitAI\config.json with last_update data.
INFO: Config file C:\Users\mrgre\StoryToolkitAI\config.json saved.
INFO: Running StoryToolkitAI version 0.19.4 (standalone)
numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
C:\Users\mrgre\AppData\Local\Programs\StoryToolkitAI\numpy\.libs\libopenblas.FB5AE2TYXYH2IJRDKGDGQ3XBKLKTF43H.gfortran-win_amd64.dll
C:\Users\mrgre\AppData\Local\Programs\StoryToolkitAI\numpy\.libs\libopenblas64__v0.3.21-gcc_10_3_0.dll
  warnings.warn("loaded more than 1 DLL from .libs:"
INFO: Starting StoryToolkitAI GUI
ERROR: Traceback (most recent call last):
  File "storytoolkitai\__main__.py", line 57, in <module>
  File "pkg_resources\__init__.py", line 909, in require
  File "pkg_resources\__init__.py", line 800, in resolve
pkg_resources.ContextualVersionConflict: (decorator 5.1.1 (c:\users\mrgre\appdata\local\programs\storytoolkitai), Requirement.parse('decorator<5.0,>=4.0.2'), {'moviepy'})

WARNING: Some of the packages required to run StoryToolkitAI are missing from your Python environment.

WARNING:
If you are running the standalone version of the app, please report this error to the developers together with the log file found at: C:\Users\mrgre\StoryToolkitAI\app.log

usage: StoryToolkitAI.0.19.4.WIN.exe [-h] [--mode {gui,cli}] [--debug] [--noresolve]
                                     [--skip-python-check] [--skip-update-check]
                                     [--output-dir OUTPUT_DIR]
                                     [--resolve-render "KEY1=VALUE1", "KEY2=VALUE2", ..."]
                                     [--resolve-render-job "JOB_ID"]
                                     [--resolve-render-data "JSON_DATA"]
StoryToolkitAI.0.19.4.WIN.exe: error: unrecognized arguments: C:\Users\mrgre\AppData\Local\Programs\StoryToolkitAI\StoryToolkitAI.0.19.4.WIN.exe

_Originally posted by @co50 in https://github.com/octimot/StoryToolkitAI/issues/118#issuecomment-1628929729_

**Comment by octimot** [comment]
This was fixed starting with version 0.23.1: the installer now deletes all the files from the installation directory to prevent keeping packages that we don't need.
