### ISSUE TITLE
Exception in Tkinter callback

### ISSUE THREAD

**Issue by pantau000** [octimot/StoryToolkitAI#127]
INFO: Running StoryToolkitAI version 0.19.1
WARNING: A new version of StoryToolkitAI is available.

Use git pull to update.

Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "D:\temp\StoryToolkitAI\StoryToolkitAI\storytoolkitai\..\storytoolkitai\ui\toolkit_ui.py", line 1621, in <lambda>
    self.windows[window_id].bind("<FocusIn>", lambda event: self._focused_window(window_id))
  File "D:\temp\StoryToolkitAI\StoryToolkitAI\storytoolkitai\..\storytoolkitai\ui\toolkit_ui.py", line 1795, in _focused_window
    self.on_window_focus_change()
  File "D:\temp\StoryToolkitAI\StoryToolkitAI\storytoolkitai\..\storytoolkitai\ui\toolkit_ui.py", line 1812, in on_window_focus_change
    self.UI_menus.update_current_window_references()
  File "D:\temp\StoryToolkitAI\StoryToolkitAI\storytoolkitai\..\storytoolkitai\ui\menu.py", line 87, in update_current_window_references
    self.load_menu_for_main()
  File "D:\temp\StoryToolkitAI\StoryToolkitAI\storytoolkitai\..\storytoolkitai\ui\menu.py", line 103, in load_menu_for_main
    self.windowsmenu.entryconfig('Keep window on top', state=DISABLED)
AttributeError: 'UImenus' object has no attribute 'windowsmenu'
INFO: Starting StoryToolkitAI GUI

**Comment by octimot** [comment]
Hey,

This was fixed in the latest versions and will be available soon-ish on the public repo too.

Cheers
