### ISSUE TITLE
Error launching through CMD

### ISSUE THREAD

**Issue by GypsyAcidQueen** [octimot/StoryToolkitAI#149]
Hi there,

I've been through all the steps on the installation page but when I try to launch it throws this error:

Traceback (most recent call last):
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\StorytoolkitAI\StoryToolkitAI\storytoolkitai\__main__.py", line 123, in <module>
    from storytoolkitai.core.toolkit_ops.toolkit_ops import ToolkitOps
  File "C:\Program Files\StorytoolkitAI\StoryToolkitAI\storytoolkitai\..\storytoolkitai\core\toolkit_ops\toolkit_ops.py", line 27, in <module>
    from .assistant import ToolkitAssistant, AssistantUtils
  File "C:\Program Files\StorytoolkitAI\StoryToolkitAI\storytoolkitai\..\storytoolkitai\core\toolkit_ops\assistant.py", line 48, in <module>
    class AssistantResponse(BaseModel):
  File "C:\Program Files\StorytoolkitAI\StoryToolkitAI\storytoolkitai\..\storytoolkitai\core\toolkit_ops\assistant.py", line 55, in AssistantResponse
    def check_completion_or_error(cls, values):
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python310\lib\site-packages\pydantic\deprecated\class_validators.py", line 222, in root_validator
    return root_validator()(*__args)  # type: ignore
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python310\lib\site-packages\pydantic\deprecated\class_validators.py", line 228, in root_validator
    raise PydanticUserError(
pydantic.errors.PydanticUserError: If you use `@root_validator` with pre=False (the default) you MUST specify `skip_on_failure=True`. Note that `@root_validator` is deprecated and should be replaced with `@model_validator`.

For further information visit https://errors.pydantic.dev/2.0/u/root-validator-pre-skip

Any help appreciated!

**Comment by octimot** [comment]
Could you say what prompt were you trying to send to the assistant?

Cheers!

**Comment by octimot** [comment]
Also, which version of pydantic do you currently have installed?

You can find out that if you do `pip list` in the virtual environment you use for the tool.

**Comment by GypsyAcidQueen** [comment]
> Could you say what prompt were you trying to send to the assistant?
> 
> Cheers!

Hi there, thanks for the quick reply! I wasn't using the assistant actually, I was just trying to launch the tool after installing, but it wouldn't launch. I decided to download the standalone version instead and it is working (but I'm not sure if the version numbers are the same - 0.19.5)

For pydantic I'm getting

pydantic              2.0
pydantic_core         2.0.1

**Comment by octimot** [comment]
Alright, thanks! I'll try to push a patch in a few minutes.

**Comment by octimot** [comment]
The issue is that I haven't made the pydantic version clear in the requirements.txt and you're installation directly assumed the latest version.

I wrote a temporary solution and pushed it to the repo.

First, do this:
```
pip uninstall pydantic spacy en-core-web-sm en-core-web-lg 
pip install --upgrade pydantic==1.10.8
```
Then `git pull` the new commit from the repo.

Then try to restart.

**Comment by GypsyAcidQueen** [comment]
> Alright, thanks! I'll try to push a patch in a few minutes.

Okay perfect thanks so much octimot, that's completely fixed the issue! It auto updated a bunch of things and successfully launched version 0.22.0

**Comment by octimot** [comment]
Cool, thanks for reporting this!

Cheers
