### ISSUE TITLE
Resolve Integration - ModuleNotFoundError

### ISSUE THREAD

**Issue by Mindboxer** [octimot/StoryToolkitAI#160]
I have installed StoryToolkitAI and am able to start the standalone program on windows, but when I try to connect to Resolve API from the storyToolkit menu, I get several errors in the console.
I have checked that I have only one version of python installed (3.10).

What can I do to try to fix this? 
I'm not really familiar with python, so I'm not sure if I'm missing something. 

> Exception in Tkinter callback
Traceback (most recent call last):
  File "storytoolkitai\integrations\mots_resolve.py", line 166, in get_resolve
ModuleNotFoundError: No module named 'DaVinciResolveScript'

> During handling of the above exception, another exception occurred:

> Traceback (most recent call last):
  File "C:\ProgramData\Blackmagic Design\DaVinci Resolve\Support\Developer\Scripting\Modules\DaVinciResolveScript.py", line 7, in <module>
    import fusionscript as script_module
ModuleNotFoundError: No module named 'fusionscript'

> During handling of the above exception, another exception occurred:

> Traceback (most recent call last):
  File "tkinter\__init__.py", line 1921, in __call__
  File "storytoolkitai\ui\toolkit_ui.py", line 12221, in on_connect_resolve_api_press
  File "storytoolkitai\core\toolkit_ops\toolkit_ops.py", line 2850, in resolve_enable
  File "storytoolkitai\integrations\mots_resolve.py", line 68, in __init__
  File "storytoolkitai\integrations\mots_resolve.py", line 243, in get_resolve
  File "imp.py", line 172, in load_source
  File "<frozen importlib._bootstrap>", line 719, in _load
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\ProgramData\Blackmagic Design\DaVinci Resolve\Support\Developer\Scripting\Modules\DaVinciResolveScript.py", line 29, in <module>
    script_module = imp.load_dynamic("fusionscript", path + "fusionscript" + ext)
  File "imp.py", line 343, in load_dynamic
  File "<frozen importlib._bootstrap>", line 719, in _load
  File "<frozen importlib._bootstrap>", line 674, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1176, in create_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
SystemError: initialization of fusionscript failed without raising an exception

**Comment by octimot** [comment]
Please attach the log, at least from the start of the tool to the error. You can find it using the main menu: File -> Open Configuration Directory

Cheers

**Comment by Mindboxer** [comment]
[app.log](https://github.com/octimot/StoryToolkitAI/files/14362672/app.log)

Looking at the log, it seems like it is not finding py on this machine.... 
I guess I should try to reinstall python first?

**Comment by octimot** [comment]
It looks so, yes. 

You should use the official Python installer, for e.g. the one found here: https://www.python.org/downloads/release/python-31011/

Installing from the windows store or non-official sources will most likely not work...

> 1. Download and install Python
Download the latest Python 3.10 version from [the official Python website](https://www.python.org/downloads/).
Note: Do not use the Python installers available from the Windows Store. Only use other Python installers / versions if you know what you're doing.
Then simply install it on your machine using the default settings.
To check if you installed the right version, open the Command Prompt and run:
py --version
Something like Python 3.10.11 should appear. Anything else besides 3.10.X means that you're in uncharted territories! If that is the case, we recommend uninstalling all Python versions (if you don't need them of course) and reinstalling Python 3.10.

(excerpt from [Installing the tool from source -> Windows -> Step 1](https://github.com/octimot/StoryToolkitAI/blob/main/INSTALLATION.md#1-download-and-install-python).

**Comment by Mindboxer** [comment]
Thank you! It seemed to work after installing that way!

**Comment by octimot** [comment]
Great! Thanks for the update!
