### ISSUE TITLE
Speaker Detection Keeps Failing

### ISSUE THREAD

**Issue by GypsyAcidQueen** [octimot/StoryToolkitAI#187]
When I try to run speaker detection in v 0.24, I get this error

**Comment by GypsyAcidQueen** [comment]
Update: it works fine in CMD with administrator privileges

**Comment by GypsyAcidQueen** [comment]
Update: HOWEVER, group questions is throwing this error regardless of whether the CMD has administrator privileges or not.

ERROR: Unable to execute task <bound method ToolkitOps.group_questions of <storytoolkitai.core.toolkit_ops.toolkit_ops.ToolkitOps object at 0x00000189570B2920>> for queue item TranslationofLiJingQiA.wav(GroupQuestions)-1721907363.7646039
Traceback (most recent call last):
File "E:\StoryToolkitAI\venv\lib\site-packages\transformers\utils\hub.py", line 402, in cached_file
resolved_file = hf_hub_download(
File "E:\StoryToolkitAI\venv\lib\site-packages\huggingface_hub\utils_deprecation.py", line 101, in inner_f
return f(*args, **kwargs)
File "E:\StoryToolkitAI\venv\lib\site-packages\huggingface_hub\utils_validators.py", line 106, in inner_fn
validate_repo_id(arg_value)
File "E:\StoryToolkitAI\venv\lib\site-packages\huggingface_hub\utils_validators.py", line 160, in validate_repo_id
raise HFValidationError(
huggingface_hub.errors.HFValidationError: Repo id must use alphanumeric chars or '-', '', '.', '--' and '..' are forbidden, '-' and '.' cannot start or end the name, max length is 96: ''.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "E:\StoryToolkitAI\StoryToolkitAI\storytoolkitai..\storytoolkitai\core\toolkit_ops\processing_queue.py", line 739, in execute_item_tasks
kwargs = task(**{**kwargs, **item})
File "E:\StoryToolkitAI\StoryToolkitAI\storytoolkitai..\storytoolkitai\core\toolkit_ops\toolkit_ops.py", line 2491, in group_questions
classified_question_segments = self.classify_segments(
File "E:\StoryToolkitAI\StoryToolkitAI\storytoolkitai..\storytoolkitai\core\toolkit_ops\toolkit_ops.py", line 2305, in classify_segments
classifier = pipeline('zero-shot-classification',
File "E:\StoryToolkitAI\venv\lib\site-packages\transformers\pipelines_init_.py", line 768, in pipeline
resolved_config_file = cached_file(
File "E:\StoryToolkitAI\venv\lib\site-packages\transformers\utils\hub.py", line 466, in cached_file
raise EnvironmentError(
OSError: Incorrect path_or_model_id: ''. Please provide either the path to a local folder or the repo_id of a model on the Hub.
