### ISSUE TITLE
Davinci Resolve crashes when clicking on transcript timeline

### ISSUE THREAD

**Issue by aparraga** [octimot/StoryToolkitAI#29]
This is what I can see in the console:

```
2022-12-01 20:45:27.200 StoryToolkitAI.0.17.5.M1[73259:2499663] +[CATransaction synchronize] called within transaction
INFO: Saving into /Users/antonioparraga/Desktop and starting render.
Exception in Tkinter callback
Traceback (most recent call last):
  File "/Users/antonioparraga/Desktop/StoryToolkitAI.0.17.5.M1.app/Contents/Resources/lib/python3.9/tkinter/__init__.py", line 1892, in __call__
  File "/Users/antonioparraga/Desktop/StoryToolkitAI.0.17.5.M1.app/Contents/Resources/app.py", line 2794, in <lambda>
  File "/Users/antonioparraga/Desktop/StoryToolkitAI.0.17.5.M1.app/Contents/Resources/app.py", line 6084, in prepare_transcription_file
  File "mots_resolve.pyc", line 985, in render_timeline
TypeError: 'NoneType' object is not callable
```

Any help could be appreciate

**Comment by octimot** [comment]
Try to create the transcription_WAV preset and see if it still crashes. Instructions here: [Resolve "transcription_WAV" Preset](https://github.com/octimot/StoryToolkitAI#resolve-transcription_wav-preset)

**Comment by aparraga** [comment]
After that error, I can see this traceback:

```
Traceback (most recent call last):
  File "/Users/antonioparraga/Desktop/StoryToolkitAI.0.17.5.M1.app/Contents/Resources/app.py", line 7691, in poll_resolve_data
KeyError: 'currentTimeline'
```

It seems like the key currentTimeline at   ```resolve_data['currentTimeline']``` does not exists. Any clue?

**Comment by aparraga** [comment]
and I have selected in Davinci a timeline, not sure if I have to do anything else in Davinci

**Comment by aparraga** [comment]
And finally, with the audio present, it works. Not sure what's wrong...

**Comment by aparraga** [comment]
Now the problem is that, after clicking on the start button, it does not transcribe, and I can see this new error on console:

```
ERROR: Missing parameters to add file to transcription queue
```

This is the full log:

```
2022-12-01 21:53:27.466 StoryToolkitAI.0.17.5.M1[85316:2603114] +[CATransaction synchronize] called within transaction
INFO: Saving into /Users/antonioparraga/Desktop and starting render.
INFO: Starting render
ERROR: Missing parameters to add file to transcription queue
```

**Comment by octimot** [comment]
If you check the file it renders from Resolve, do you have audio? Do you actually hear something when playing back the file in another player?

Cheers!
