### ISSUE TITLE
Resampling error

### ISSUE THREAD

**Issue by hiddenpeanuts** [octimot/StoryToolkitAI#65]
I'm getting this up and running for the first time today - 0.17.5 standalone on Windows.

I'm still experimenting and throwing random files at it that I had on hand. Most of the time it works just fine. I've run it successfully on a video and mp3. But on some (multiple) mp3s, I get the error below. I did install FFMPEG - did I miss a step?

ERROR: Traceback (most recent call last):
  File "app.py", line 6486, in transcribe_from_queue
  File "app.py", line 6778, in whisper_transcribe
  File "librosa\util\decorators.py", line 88, in inner_f
    return f(*args, **kwargs)
  File "librosa\core\audio.py", line 179, in load
    y = resample(y, orig_sr=sr_native, target_sr=sr, res_type=res_type)
  File "librosa\util\decorators.py", line 88, in inner_f
    return f(*args, **kwargs)
  File "librosa\core\audio.py", line 647, in resample
    y_hat = resampy.resample(y, orig_sr, target_sr, filter=res_type, axis=-1)
  File "resampy\core.py", line 117, in resample
    raise ValueError(
ValueError: Input signal length=0 is too small to resample from 44100->16000

![image](https://user-images.githubusercontent.com/2480976/223166325-597073c8-f92b-4d57-bee9-1bfa7e02712d.png)

**Comment by octimot** [comment]
Hey there! Thanks for the feedback!

How many channels does the audio file have?

**Comment by hiddenpeanuts** [comment]
I hadn't thought to look! I don't think I see a pattern though:

File 1, fails: 1 channel, 44100Hz
File 2, fails:  2 channel, 44100Hz
File 3, succeeds: 2 channel, 44100Hz
File 4, succeeds: 2 channel, 16000Hz

I should also say that I'm completely amazed by results on the successful ones. Incredible work.

**Comment by octimot** [comment]
@hiddenpeanuts Are you still experiencing this in the latest standalone version?

Cheers

**Comment by hiddenpeanuts** [comment]
I'm not! I haven't run into it since the latest release.
