### ISSUE TITLE
Failure to load after recent update

### ISSUE THREAD

**Issue by GypsyAcidQueen** [octimot/StoryToolkitAI#71]
Hi there,

After running git pull and updating to the latest verison, I'm getting this error when trying to run the program

INFO: Running StoryToolkitAI version 0.17.15
INFO: Using cuda for Torch / Whisper.
INFO: Resolve API module found and loaded
INFO: Resolve API module found and loaded
Traceback (most recent call last):
  File "C:\***", line 12049, in <module>
    app_UI = toolkit_UI(toolkit_ops_obj=toolkit_ops_obj, stAI=stAI,
  File "C:\***", line 2994, in __init__
    photo = tk.PhotoImage(file = 'StoryToolkitAI.png')
  File "C:\***", line 4064, in __init__
    Image.__init__(self, 'photo', name, cnf, master, **kw)
  File "C:\***", line 4009, in __init__
    self.tk.call(('image', 'create', imgtype, name,) + options)
_tkinter.TclError: couldn't open "StoryToolkitAI.png": no such file or directory

(venv) C:\***>

After this, the GUI does not launch. 

Any help appreciated, thanks!

**Comment by yeonjae0607** [comment]
Same here

**Comment by octimot** [comment]
Just pushed a fix. 

Can you try another `git pull` and let me know if it works?

**Comment by GypsyAcidQueen** [comment]
> Just pushed a fix.
> 
> Can you try another `git pull` and let me know if it works?

Amazing thank you!! Works again.

**Comment by octimot** [comment]
Cool, thanks for the feedback!
