### ISSUE TITLE
StoryToolkitAI error message when transcribing

### ISSUE THREAD

**Issue by Andreotto89** [octimot/StoryToolkitAI#76]
Hi
I get the following error message when I try to transcribe the timeline in DaVinci.
I am using Windows 11 and Davinci Resolve 18.1.4.
Here is the error message in the command line:

INFO: Resolve API module found and loaded
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Andre\AppData\Local\Programs\Python\Python39\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "F:\Test\StoryToolkitAI\app.py", line 3652, in <lambda>
    command=lambda: self.toolkit_ops_obj.prepare_transcription_file(
  File "F:\Test\StoryToolkitAI\app.py", line 8832, in prepare_transcription_file
    last_target_dir = self.stAI.get_project_setting(project_name=current_project, setting_key='last_target_dir')
  File "F:\Test\StoryToolkitAI\app.py", line 11636, in get_project_setting
    self.project_settings = self.get_project_settings(project_name=project_name)
  File "F:\Test\StoryToolkitAI\app.py", line 11586, in get_project_settings
    if os.path.exists(project_settings_path):
  File "C:\Users\Andre\AppData\Local\Programs\Python\Python39\lib\genericpath.py", line 19, in exists
    os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType

and here is the form the log:
2023-03-26 16:03:50,487 - StAI - DEBUG: All package requirements met. (app.py:167)
2023-03-26 16:03:50,488 - StAI - DEBUG: Loading config file C:\Users\Andre\StoryToolkitAI\config.json. (app.py:11553)
2023-03-26 16:03:50,585 - StAI - INFO: [1m[4mRunning StoryToolkitAI version 0.17.16  (app.py:11370)
2023-03-26 16:03:50,600 - StAI - INFO: Using cuda for Torch / Whisper. (app.py:8737)
2023-03-26 16:03:50,600 - StAI - DEBUG: MotsResolve module initialized. (mots_resolve.py:42)
2023-03-26 16:03:50,612 - StAI - WARNING: Found the following Python versions on this machine: 3.9, 3.8 (mots_resolve.py:114)
2023-03-26 16:03:50,612 - StAI - WARNING: Current installation runs on Python version 3.9. (mots_resolve.py:116)
2023-03-26 16:03:50,613 - StAI - WARNING: Unable be able to connect to DaVinci Resolve API on Windows if this is the case. (mots_resolve.py:118)
2023-03-26 16:03:50,613 - StAI - WARNING: Please uninstall all Python versions except version 3.9. (mots_resolve.py:119)
2023-03-26 16:03:50,613 - StAI - ERROR: Python version check failed. Resolve API connection disabled. (mots_resolve.py:70)
2023-03-26 16:03:50,613 - StAI - DEBUG: Resolve API module not available on this machine. Aborting Resolve API polling until StoryToolkitAI restart. (app.py:10943)
2023-03-26 16:03:50,656 - StAI - DEBUG: Could not load StoryToolkitAI icon. (app.py:3001)
2023-03-26 16:03:50,662 - StAI - DEBUG: Running with TK 8.6.12 (app.py:3009)
2023-03-26 16:03:51,169 - StAI - INFO: Starting StoryToolkitAI GUI (app.py:3712)
2023-03-26 16:04:13,050 - StAI - DEBUG: Trying to load DaVinciResolveScript module... (mots_resolve.py:139)
2023-03-26 16:04:13,051 - StAI - DEBUG: Found DaVinci Resolve at the default location: C:\Program Files\Blackmagic Design\DaVinci Resolve\ (mots_resolve.py:204)
2023-03-26 16:04:13,051 - StAI - DEBUG: Unable to find module DaVinciResolveScript from PYTHONPATH - trying default locations next (mots_resolve.py:216)
2023-03-26 16:04:13,070 - StAI - INFO: Resolve API module found and loaded (mots_resolve.py:238)

**Comment by octimot** [comment]
Thanks for the feedback!

Can you try to run the app with --skip-python-check ?

**Comment by Andreotto89** [comment]
Thanks for the help
The new Standalone version is working fine!

**Comment by octimot** [comment]
Cool! 

I did discover a bug in the way project folders are checked internally, based on your report so thanks! I'll fix that as soon as possible!
